name: windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Set permissions at the job level.
permissions: {}

jobs:
  windows:
    runs-on: windows-2022
    permissions:
      contents: read
    strategy:
      matrix:
        cc: ['cl', 'clang-cl']
    env:
      CC: ${{matrix.cc}}
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install dependencies
        shell: cmd
        run: |
          # Jinja2 is needed for merge-modes tests
          python -m pip install --upgrade meson Jinja2
          choco install -y winflexbison3
      - name: Setup
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          meson setup --backend=vs -Denable-wayland=false -Denable-x11=false -Denable-docs=false -Denable-xkbregistry=false build
      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          meson compile -C build
      - name: Test
        run:
          meson test -C build --print-errorlogs
